# Generated by Django 4.0.3 on 2022-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Message',
        ),
        migrations.AddField(
            model_name='notice',
            name='Title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
